"use client";

import dynamic from "next/dynamic";
import { useState } from "react";
import { api } from "@/lib/client";
import { driveEnabled, saveApplicationToDrive } from "@/lib/drive";
import { storage } from "@/lib/storage";
import type {
  ApplicationRecord,
  Job,
  MatchResult,
  ParsedJob,
  Profile,
  ReferralQA,
  TailoredResume,
} from "@/lib/types";
import { Chip, CopyButton, ErrorBanner, SectionTitle, Spinner } from "./ui";

type Letters = Partial<Record<"coverLetter" | "recruiterEmail" | "referralNote", string>>;

/** Bundle whatever's been generated into one readable Markdown application doc. */
function buildMarkdown(
  job: Job,
  match: MatchResult | null,
  tailored: TailoredResume | null,
  letters: Letters,
  qa: ReferralQA | null,
): string {
  const L: string[] = [];
  L.push(`# ${job.title || "Role"} — ${job.company || "Company"}`, "");
  if (job.url) L.push(`- Posting: ${job.url}`);
  if (match) {
    L.push(`- Match: ${match.score}/100 — ${match.verdict}`);
    if (match.summary) L.push("", match.summary);
    if (match.matchedKeywords?.length) L.push("", `**Matched:** ${match.matchedKeywords.join(", ")}`);
    if (match.missingKeywords?.length) L.push(`**Missing:** ${match.missingKeywords.join(", ")}`);
  }
  if (tailored?.emphasis?.length) L.push("", "## Tailored resume — emphasis", tailored.emphasis.join(", "));
  if (tailored?.changeNotes?.length)
    L.push("", "## What changed", ...tailored.changeNotes.map((n) => `- ${n}`));
  const letterTitles: Record<string, string> = {
    coverLetter: "Cover letter",
    recruiterEmail: "Recruiter email",
    referralNote: "Referral note",
  };
  for (const [k, v] of Object.entries(letters)) {
    if (v) L.push("", `## ${letterTitles[k] ?? k}`, v);
  }
  if (qa?.items?.length) {
    L.push("", "## Referral Q&A");
    for (const it of qa.items) L.push("", `**${it.question}**`, it.answer);
  }
  L.push("", "---", `_Generated by OfferBen on ${new Date().toLocaleString()}_`);
  return L.join("\n");
}

const ResumeDownloadButton = dynamic(() => import("./ResumePdf"), {
  ssr: false,
  loading: () => (
    <button type="button" className="btn-ghost" disabled>
      Preparing…
    </button>
  ),
});

type LetterKey = "coverLetter" | "recruiterEmail" | "referralNote";

const LETTER_CARDS: { key: LetterKey; title: string; desc: string }[] = [
  { key: "coverLetter", title: "Cover letter", desc: "Tailored, ~300 words." },
  { key: "recruiterEmail", title: "Recruiter email", desc: "Short cold outreach with a subject line." },
  { key: "referralNote", title: "Referral note", desc: "LinkedIn DM asking for a referral." },
];

function sanitize(s: string): string {
  return (s || "").replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "") || "resume";
}

export function GenerateStep({
  profile,
  job,
  parsed,
  match,
  onBack,
  onTrackerChange,
}: {
  profile: Profile;
  job: Job;
  parsed: ParsedJob | null;
  match: MatchResult | null;
  onBack: () => void;
  onTrackerChange?: (list: ApplicationRecord[]) => void;
}) {
  const [tailored, setTailored] = useState<TailoredResume | null>(null);
  const [letters, setLetters] = useState<Partial<Record<LetterKey, string>>>({});
  const [qa, setQa] = useState<ReferralQA | null>(null);
  const [loading, setLoading] = useState<Record<string, boolean>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [driveBusy, setDriveBusy] = useState(false);
  const [driveMsg, setDriveMsg] = useState<string | null>(null);
  const [driveUrl, setDriveUrl] = useState<string | null>(null);

  const hasContent = Boolean(tailored || Object.values(letters).some(Boolean) || qa);

  async function saveToDrive() {
    setDriveBusy(true);
    setDriveMsg("Saving…");
    try {
      const id = job.url || `${job.company}::${job.title}`;
      const existing = storage.loadApplications().find((a) => a.id === id);
      const markdown = buildMarkdown(job, match, tailored, letters, qa);
      const saved = await saveApplicationToDrive(
        { title: job.title, company: job.company, fileId: existing?.driveFileId, markdown },
        setDriveMsg,
      );
      const now = new Date().toISOString();
      const list = storage.saveApplication({
        id,
        title: job.title,
        company: job.company,
        url: job.url,
        score: match?.score,
        verdict: match?.verdict,
        status: existing?.status ?? "saved",
        notes: existing?.notes,
        driveFileId: saved.fileId,
        driveUrl: saved.url,
        createdAt: existing?.createdAt ?? now,
        updatedAt: now,
      });
      onTrackerChange?.(list);
      setDriveUrl(saved.url ?? null);
      setDriveMsg("✓ Saved to your Drive");
    } catch (err) {
      setDriveMsg(err instanceof Error ? err.message : "Save failed");
    } finally {
      setDriveBusy(false);
    }
  }

  function setBusy(key: string, v: boolean) {
    setLoading((s) => ({ ...s, [key]: v }));
  }
  function setErr(key: string, v: string) {
    setErrors((s) => ({ ...s, [key]: v }));
  }

  async function runTailor() {
    setErr("tailor", "");
    setBusy("tailor", true);
    try {
      const { resume } = await api.tailor({
        profile,
        job,
        parsed: parsed ?? undefined,
        match: match ?? undefined,
      });
      setTailored(resume);
    } catch (err) {
      setErr("tailor", err instanceof Error ? err.message : "Failed.");
    } finally {
      setBusy("tailor", false);
    }
  }

  async function runLetter(key: LetterKey) {
    setErr(key, "");
    setBusy(key, true);
    try {
      const { text } = await api.letter({ profile, job, kind: key });
      setLetters((s) => ({ ...s, [key]: text }));
    } catch (err) {
      setErr(key, err instanceof Error ? err.message : "Failed.");
    } finally {
      setBusy(key, false);
    }
  }

  async function runQA() {
    setErr("qa", "");
    setBusy("qa", true);
    try {
      const { qa: result } = await api.referralQA({ profile, job });
      setQa(result);
    } catch (err) {
      setErr("qa", err instanceof Error ? err.message : "Failed.");
    } finally {
      setBusy("qa", false);
    }
  }

  const fileName = `${sanitize(profile.basics.name)}_${sanitize(job.company || job.title)}.pdf`;
  const resumeProfile = tailored?.profile ?? profile;

  return (
    <div className="space-y-6">
      {/* Tailored resume */}
      <div className="card p-5">
        <SectionTitle hint="Truthful rewrite, reordered for this role">
          Tailored resume
        </SectionTitle>

        {!tailored ? (
          <div className="space-y-3">
            <p className="text-sm text-slate-400">
              Rewrite and reorder your resume to emphasize what this job wants —
              without fabricating anything.
            </p>
            <button
              type="button"
              className="btn-primary"
              disabled={loading.tailor}
              onClick={runTailor}
            >
              {loading.tailor ? <Spinner /> : null}
              {loading.tailor ? "Tailoring…" : "Generate tailored resume"}
            </button>
            <ErrorBanner message={errors.tailor} />
          </div>
        ) : (
          <div className="space-y-4">
            {tailored.emphasis.length ? (
              <div>
                <div className="label">Emphasized</div>
                <div className="flex flex-wrap gap-1.5">
                  {tailored.emphasis.map((k, i) => (
                    <Chip key={i} tone="brand">
                      {k}
                    </Chip>
                  ))}
                </div>
              </div>
            ) : null}

            {tailored.changeNotes.length ? (
              <div>
                <div className="label">What changed</div>
                <ul className="list-disc space-y-1 pl-5 text-sm text-slate-300">
                  {tailored.changeNotes.map((n, i) => (
                    <li key={i}>{n}</li>
                  ))}
                </ul>
              </div>
            ) : null}

            <TailoredPreview resume={tailored} />

            <div className="flex flex-wrap items-center gap-2">
              <ResumeDownloadButton profile={resumeProfile} fileName={fileName} />
              <button
                type="button"
                className="btn-ghost"
                disabled={loading.tailor}
                onClick={runTailor}
              >
                {loading.tailor ? <Spinner /> : null} Regenerate
              </button>
            </div>
            <ErrorBanner message={errors.tailor} />
          </div>
        )}
      </div>

      {/* Letters */}
      <div className="grid gap-4 md:grid-cols-2">
        {LETTER_CARDS.map((card) => (
          <div key={card.key} className="card p-5">
            <SectionTitle hint={card.desc}>{card.title}</SectionTitle>
            {letters[card.key] ? (
              <div className="space-y-2">
                <div className="max-h-64 overflow-auto whitespace-pre-wrap rounded-lg border border-white/10 bg-slate-900/50 p-3 text-sm text-slate-200 scroll-thin">
                  {letters[card.key]}
                </div>
                <div className="flex gap-2">
                  <CopyButton text={letters[card.key] as string} />
                  <button
                    type="button"
                    className="btn-ghost px-2.5 py-1 text-xs"
                    disabled={loading[card.key]}
                    onClick={() => runLetter(card.key)}
                  >
                    Regenerate
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-2">
                <button
                  type="button"
                  className="btn-ghost"
                  disabled={loading[card.key]}
                  onClick={() => runLetter(card.key)}
                >
                  {loading[card.key] ? <Spinner /> : null}
                  {loading[card.key] ? "Writing…" : `Generate ${card.title.toLowerCase()}`}
                </button>
                <ErrorBanner message={errors[card.key]} />
              </div>
            )}
          </div>
        ))}

        {/* Referral Q&A */}
        <div className="card p-5">
          <SectionTitle hint="Likely referral questions + draft answers">
            Referral Q&amp;A
          </SectionTitle>
          {qa && qa.items.length ? (
            <div className="space-y-3">
              <div className="max-h-64 space-y-3 overflow-auto pr-1 scroll-thin">
                {qa.items.map((item, i) => (
                  <div key={i}>
                    <div className="text-sm font-medium text-white">
                      {item.question}
                    </div>
                    <div className="text-sm text-slate-300">{item.answer}</div>
                  </div>
                ))}
              </div>
              <button
                type="button"
                className="btn-ghost px-2.5 py-1 text-xs"
                disabled={loading.qa}
                onClick={runQA}
              >
                Regenerate
              </button>
            </div>
          ) : (
            <div className="space-y-2">
              <button
                type="button"
                className="btn-ghost"
                disabled={loading.qa}
                onClick={runQA}
              >
                {loading.qa ? <Spinner /> : null}
                {loading.qa ? "Drafting…" : "Generate referral Q&A"}
              </button>
              <ErrorBanner message={errors.qa} />
            </div>
          )}
        </div>
      </div>

      <div className="flex items-center justify-between gap-3">
        <button type="button" className="btn-ghost" onClick={onBack}>
          ← Back to match
        </button>
        {driveEnabled() ? (
          <div className="flex items-center gap-2">
            {driveMsg ? <span className="text-xs text-slate-400">{driveMsg}</span> : null}
            {driveUrl ? (
              <a
                href={driveUrl}
                target="_blank"
                rel="noreferrer"
                className="btn-ghost px-2.5 py-1 text-xs"
              >
                Open in Drive ↗
              </a>
            ) : null}
            <button
              type="button"
              className="btn-primary"
              disabled={driveBusy || !hasContent}
              onClick={saveToDrive}
              title={hasContent ? "Save this application to My Drive/OfferBen" : "Generate something first"}
            >
              {driveBusy ? <Spinner /> : null} Save to Drive
            </button>
          </div>
        ) : null}
      </div>
    </div>
  );
}

function TailoredPreview({ resume }: { resume: TailoredResume }) {
  const p = resume.profile;
  return (
    <div className="rounded-lg border border-white/10 bg-slate-900/40 p-4 text-sm">
      {p.basics.summary ? (
        <p className="text-slate-200">{p.basics.summary}</p>
      ) : null}
      {p.work.slice(0, 3).map((w, i) => (
        <div key={i} className="mt-3">
          <div className="font-medium text-white">
            {w.position}
            {w.name ? ` · ${w.name}` : ""}
          </div>
          <ul className="mt-1 list-disc space-y-0.5 pl-5 text-slate-300">
            {w.highlights.slice(0, 3).map((h, j) => (
              <li key={j}>{h}</li>
            ))}
          </ul>
        </div>
      ))}
      <p className="mt-3 text-xs text-slate-500">
        Download the PDF for the full, formatted, ATS-safe resume.
      </p>
    </div>
  );
}
