"use client";

import dynamic from "next/dynamic";
import { useState } from "react";
import { api } from "@/lib/client";
import { driveEnabled, saveApplicationToDrive } from "@/lib/drive";
import { profileToLatex } from "@/lib/latex";
import { storage } from "@/lib/storage";
import type {
  ApplicationRecord,
  DroppedItem,
  InterviewPrep,
  Job,
  MatchResult,
  ParsedJob,
  Profile,
  ReferralQA,
  TailoredResume,
} from "@/lib/types";
import { Chip, CopyButton, ErrorBanner, SectionTitle, Spinner } from "./ui";

type Letters = Partial<Record<"coverLetter" | "recruiterEmail" | "referralNote", string>>;

/** Bundle whatever's been generated into one readable Markdown application doc. */
function buildMarkdown(
  job: Job,
  match: MatchResult | null,
  tailored: TailoredResume | null,
  letters: Letters,
  qa: ReferralQA | null,
  prep: InterviewPrep | null,
): string {
  const L: string[] = [];
  L.push(`# ${job.title || "Role"} — ${job.company || "Company"}`, "");
  if (job.url) L.push(`- Posting: ${job.url}`);
  if (match) {
    L.push(`- Match: ${match.score}/100 — ${match.verdict}`);
    if (match.summary) L.push("", match.summary);
    if (match.matchedKeywords?.length) L.push("", `**Matched:** ${match.matchedKeywords.join(", ")}`);
    if (match.missingKeywords?.length) L.push(`**Missing:** ${match.missingKeywords.join(", ")}`);
  }
  if (tailored?.emphasis?.length) L.push("", "## Tailored resume — emphasis", tailored.emphasis.join(", "));
  if (tailored?.changeNotes?.length)
    L.push("", "## What changed", ...tailored.changeNotes.map((n) => `- ${n}`));
  const letterTitles: Record<string, string> = {
    coverLetter: "Cover letter",
    recruiterEmail: "Recruiter email",
    referralNote: "Referral note",
  };
  for (const [k, v] of Object.entries(letters)) {
    if (v) L.push("", `## ${letterTitles[k] ?? k}`, v);
  }
  if (qa?.items?.length) {
    L.push("", "## Referral Q&A");
    for (const it of qa.items) L.push("", `**${it.question}**`, it.answer);
  }
  if (prep?.items?.length) {
    L.push("", "## Interview prep");
    for (const it of prep.items) L.push("", `**[${it.type}] ${it.question}**`, it.answer);
  }
  L.push("", "---", `_Generated by OfferBen on ${new Date().toLocaleString()}_`);
  return L.join("\n");
}

const ResumeDownloadButton = dynamic(() => import("./ResumePdf"), {
  ssr: false,
  loading: () => (
    <button type="button" className="btn-ghost" disabled>
      Preparing…
    </button>
  ),
});

type LetterKey = "coverLetter" | "recruiterEmail" | "referralNote";

const LETTER_CARDS: { key: LetterKey; title: string; desc: string }[] = [
  { key: "coverLetter", title: "Cover letter", desc: "Tailored, ~300 words." },
  { key: "recruiterEmail", title: "Recruiter email", desc: "Short cold outreach with a subject line." },
  { key: "referralNote", title: "Referral note", desc: "LinkedIn DM asking for a referral." },
];

function sanitize(s: string): string {
  return (s || "").replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "") || "resume";
}

function downloadText(text: string, filename: string, type: string): void {
  const blob = new Blob([text], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** Open the LaTeX in a fresh Overleaf project (form POST, no infra). */
function openInOverleaf(tex: string): void {
  const form = document.createElement("form");
  form.action = "https://www.overleaf.com/docs";
  form.method = "POST";
  form.target = "_blank";
  const input = document.createElement("input");
  input.type = "hidden";
  input.name = "snip";
  input.value = tex;
  form.appendChild(input);
  document.body.appendChild(form);
  form.submit();
  form.remove();
}

/** Rough rendered-length estimate (lines → pages) so the user can trim to fit. */
function estimatePages(p: Profile): number {
  let lines = 6; // header
  if (p.basics.summary) lines += 1 + Math.ceil(p.basics.summary.length / 95);
  for (const w of p.work) lines += 2 + w.highlights.length;
  for (const pr of p.projects) lines += 2 + pr.highlights.length;
  lines += p.education.length;
  const skills = p.skills.flatMap((s) => (s.keywords.length ? s.keywords : s.name ? [s.name] : []));
  if (skills.length) lines += 2;
  if (p.publications.length) lines += 1 + p.publications.length;
  if (p.awards.length) lines += 1 + p.awards.length;
  return lines / 50; // ~50 lines per page
}

export function GenerateStep({
  profile,
  job,
  parsed,
  match,
  onBack,
  onTrackerChange,
}: {
  profile: Profile;
  job: Job;
  parsed: ParsedJob | null;
  match: MatchResult | null;
  onBack: () => void;
  onTrackerChange?: (list: ApplicationRecord[]) => void;
}) {
  const [tailored, setTailored] = useState<TailoredResume | null>(null);
  const [pageTarget, setPageTarget] = useState<1 | 2>(2);
  // Editable curated resume (starts from the AI's selection; the user can drop /
  // reorder items without spending another AI call).
  const [curated, setCurated] = useState<Profile | null>(null);
  const [letters, setLetters] = useState<Partial<Record<LetterKey, string>>>({});
  const [qa, setQa] = useState<ReferralQA | null>(null);
  const [prep, setPrep] = useState<InterviewPrep | null>(null);
  const [loading, setLoading] = useState<Record<string, boolean>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [driveBusy, setDriveBusy] = useState(false);
  const [driveMsg, setDriveMsg] = useState<string | null>(null);
  const [driveUrl, setDriveUrl] = useState<string | null>(null);

  const hasContent = Boolean(tailored || Object.values(letters).some(Boolean) || qa || prep);

  async function saveToDrive() {
    setDriveBusy(true);
    setDriveMsg("Saving…");
    try {
      const id = job.url || `${job.company}::${job.title}`;
      const existing = storage.loadApplications().find((a) => a.id === id);
      const markdown = buildMarkdown(job, match, tailored, letters, qa, prep);
      const saved = await saveApplicationToDrive(
        { title: job.title, company: job.company, fileId: existing?.driveFileId, markdown },
        setDriveMsg,
      );
      const now = new Date().toISOString();
      const list = storage.saveApplication({
        id,
        title: job.title,
        company: job.company,
        url: job.url,
        score: match?.score,
        verdict: match?.verdict,
        status: existing?.status ?? "saved",
        notes: existing?.notes,
        driveFileId: saved.fileId,
        driveUrl: saved.url,
        createdAt: existing?.createdAt ?? now,
        updatedAt: now,
      });
      onTrackerChange?.(list);
      setDriveUrl(saved.url ?? null);
      setDriveMsg("✓ Saved to your Drive");
    } catch (err) {
      setDriveMsg(err instanceof Error ? err.message : "Save failed");
    } finally {
      setDriveBusy(false);
    }
  }

  function setBusy(key: string, v: boolean) {
    setLoading((s) => ({ ...s, [key]: v }));
  }
  function setErr(key: string, v: string) {
    setErrors((s) => ({ ...s, [key]: v }));
  }

  async function runTailor() {
    setErr("tailor", "");
    setBusy("tailor", true);
    try {
      const { resume } = await api.tailor({
        profile,
        job,
        parsed: parsed ?? undefined,
        match: match ?? undefined,
        pageTarget,
      });
      setTailored(resume);
      setCurated(resume.profile);
    } catch (err) {
      setErr("tailor", err instanceof Error ? err.message : "Failed.");
    } finally {
      setBusy("tailor", false);
    }
  }

  async function runLetter(key: LetterKey) {
    setErr(key, "");
    setBusy(key, true);
    try {
      const { text } = await api.letter({ profile, job, kind: key });
      setLetters((s) => ({ ...s, [key]: text }));
    } catch (err) {
      setErr(key, err instanceof Error ? err.message : "Failed.");
    } finally {
      setBusy(key, false);
    }
  }

  async function runPrep() {
    setErr("prep", "");
    setBusy("prep", true);
    try {
      const { prep: result } = await api.interview({ profile, job });
      setPrep(result);
    } catch (err) {
      setErr("prep", err instanceof Error ? err.message : "Failed.");
    } finally {
      setBusy("prep", false);
    }
  }

  async function runQA() {
    setErr("qa", "");
    setBusy("qa", true);
    try {
      const { qa: result } = await api.referralQA({ profile, job });
      setQa(result);
    } catch (err) {
      setErr("qa", err instanceof Error ? err.message : "Failed.");
    } finally {
      setBusy("qa", false);
    }
  }

  const fileName = `${sanitize(profile.basics.name)}_${sanitize(job.company || job.title)}.pdf`;
  const resumeProfile = curated ?? tailored?.profile ?? profile;

  // Drop / reorder items in the curated resume (client-side, no AI call).
  function dropWork(i: number) {
    setCurated((c) => (c ? { ...c, work: c.work.filter((_, j) => j !== i) } : c));
  }
  function dropProject(i: number) {
    setCurated((c) => (c ? { ...c, projects: c.projects.filter((_, j) => j !== i) } : c));
  }
  function move<T>(arr: T[], i: number, dir: -1 | 1): T[] {
    const j = i + dir;
    if (j < 0 || j >= arr.length) return arr;
    const next = arr.slice();
    [next[i], next[j]] = [next[j], next[i]];
    return next;
  }
  function moveWork(i: number, dir: -1 | 1) {
    setCurated((c) => (c ? { ...c, work: move(c.work, i, dir) } : c));
  }
  function moveProject(i: number, dir: -1 | 1) {
    setCurated((c) => (c ? { ...c, projects: move(c.projects, i, dir) } : c));
  }
  function reorder<T>(arr: T[], from: number, to: number): T[] {
    if (from === to || from < 0 || to < 0 || from >= arr.length || to >= arr.length) return arr;
    const next = arr.slice();
    const [item] = next.splice(from, 1);
    next.splice(to, 0, item);
    return next;
  }
  function reorderWork(from: number, to: number) {
    setCurated((c) => (c ? { ...c, work: reorder(c.work, from, to) } : c));
  }
  function reorderProject(from: number, to: number) {
    setCurated((c) => (c ? { ...c, projects: reorder(c.projects, from, to) } : c));
  }
  // Re-add an AI-dropped item, using its ORIGINAL content. Keyed by title+dates
  // so two items sharing a title (e.g. two roles at the same lab) don't collide.
  function addBackWork(title: string) {
    setCurated((c) => {
      if (!c) return c;
      const present = new Set(c.work.map(workKey));
      const item = profile.work.find(
        (w) => titleMatches(title, w.position, w.name) && !present.has(workKey(w)),
      );
      return item ? { ...c, work: [...c.work, item] } : c;
    });
  }
  function addBackProject(title: string) {
    setCurated((c) => {
      if (!c) return c;
      const present = new Set(c.projects.map((p) => p.name));
      const item = profile.projects.find((p) => titleMatches(title, p.name) && !present.has(p.name));
      return item ? { ...c, projects: [...c.projects, item] } : c;
    });
  }

  return (
    <div className="space-y-6">
      {/* Tailored resume */}
      <div className="card p-5">
        <SectionTitle hint="Truthful rewrite, reordered for this role">
          Tailored resume
        </SectionTitle>

        {!tailored ? (
          <div className="space-y-3">
            <p className="text-sm text-slate-400">
              <b>Curates</b> your resume for this job — selects the most relevant
              experiences & projects, drops the ones that don&apos;t help, orders
              the strongest first, and rewords. Never fabricates.
            </p>
            <div className="flex items-center gap-2">
              <span className="label mb-0">Length</span>
              {([1, 2] as const).map((n) => (
                <button
                  key={n}
                  type="button"
                  className={pageTarget === n ? "btn-primary px-3 py-1 text-xs" : "btn-ghost px-3 py-1 text-xs"}
                  onClick={() => setPageTarget(n)}
                >
                  {n} page{n > 1 ? "s" : ""}
                </button>
              ))}
            </div>
            <button
              type="button"
              className="btn-primary"
              disabled={loading.tailor}
              onClick={runTailor}
            >
              {loading.tailor ? <Spinner /> : null}
              {loading.tailor ? "Curating…" : "Curate tailored resume"}
            </button>
            <ErrorBanner message={errors.tailor} />
          </div>
        ) : (
          <div className="space-y-4">
            <CurationEditor
              profile={resumeProfile}
              dropped={tailored.dropped}
              pageTarget={pageTarget}
              onDropWork={dropWork}
              onDropProject={dropProject}
              onMoveWork={moveWork}
              onMoveProject={moveProject}
              onReorderWork={reorderWork}
              onReorderProject={reorderProject}
              onAddWork={addBackWork}
              onAddProject={addBackProject}
            />

            <div className="flex flex-wrap items-center gap-2">
              <ResumeDownloadButton profile={resumeProfile} fileName={fileName} />
              <button
                type="button"
                className="btn-ghost"
                onClick={() => downloadText(profileToLatex(resumeProfile), `${sanitize(profile.basics.name)}_resume.tex`, "application/x-tex")}
              >
                Download .tex
              </button>
              <button
                type="button"
                className="btn-ghost"
                onClick={() => openInOverleaf(profileToLatex(resumeProfile))}
              >
                Open in Overleaf ↗
              </button>
              <button
                type="button"
                className="btn-ghost"
                disabled={loading.tailor}
                onClick={runTailor}
              >
                {loading.tailor ? <Spinner /> : null} Re-curate ({pageTarget}p)
              </button>
            </div>

            {/* Secondary detail — collapsed to keep the view clean (#25). */}
            {tailored.emphasis.length || tailored.changeNotes.length ? (
              <details className="text-sm">
                <summary className="cursor-pointer text-xs uppercase tracking-wide text-slate-400">
                  Emphasis & what changed
                </summary>
                <div className="mt-2 space-y-3">
                  {tailored.emphasis.length ? (
                    <div className="flex flex-wrap gap-1.5">
                      {tailored.emphasis.slice(0, 12).map((k, i) => (
                        <Chip key={i} tone="brand">
                          {k}
                        </Chip>
                      ))}
                    </div>
                  ) : null}
                  {tailored.changeNotes.length ? (
                    <ul className="list-disc space-y-1 pl-5 text-slate-300">
                      {tailored.changeNotes.map((n, i) => (
                        <li key={i}>{n}</li>
                      ))}
                    </ul>
                  ) : null}
                </div>
              </details>
            ) : null}
            <ErrorBanner message={errors.tailor} />
          </div>
        )}
      </div>

      {/* Letters */}
      <div className="grid gap-4 md:grid-cols-2">
        {LETTER_CARDS.map((card) => (
          <div key={card.key} className="card p-5">
            <SectionTitle hint={card.desc}>{card.title}</SectionTitle>
            {letters[card.key] ? (
              <div className="space-y-2">
                <div className="max-h-64 overflow-auto whitespace-pre-wrap rounded-lg border border-white/10 bg-slate-900/50 p-3 text-sm text-slate-200 scroll-thin">
                  {letters[card.key]}
                </div>
                <div className="flex gap-2">
                  <CopyButton text={letters[card.key] as string} />
                  <button
                    type="button"
                    className="btn-ghost px-2.5 py-1 text-xs"
                    disabled={loading[card.key]}
                    onClick={() => runLetter(card.key)}
                  >
                    Regenerate
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-2">
                <button
                  type="button"
                  className="btn-ghost"
                  disabled={loading[card.key]}
                  onClick={() => runLetter(card.key)}
                >
                  {loading[card.key] ? <Spinner /> : null}
                  {loading[card.key] ? "Writing…" : `Generate ${card.title.toLowerCase()}`}
                </button>
                <ErrorBanner message={errors[card.key]} />
              </div>
            )}
          </div>
        ))}

        {/* Referral Q&A */}
        <div className="card p-5">
          <SectionTitle hint="Likely referral questions + draft answers">
            Referral Q&amp;A
          </SectionTitle>
          {qa && qa.items.length ? (
            <div className="space-y-3">
              <div className="max-h-64 space-y-3 overflow-auto pr-1 scroll-thin">
                {qa.items.map((item, i) => (
                  <div key={i}>
                    <div className="text-sm font-medium text-white">
                      {item.question}
                    </div>
                    <div className="text-sm text-slate-300">{item.answer}</div>
                  </div>
                ))}
              </div>
              <button
                type="button"
                className="btn-ghost px-2.5 py-1 text-xs"
                disabled={loading.qa}
                onClick={runQA}
              >
                Regenerate
              </button>
            </div>
          ) : (
            <div className="space-y-2">
              <button
                type="button"
                className="btn-ghost"
                disabled={loading.qa}
                onClick={runQA}
              >
                {loading.qa ? <Spinner /> : null}
                {loading.qa ? "Drafting…" : "Generate referral Q&A"}
              </button>
              <ErrorBanner message={errors.qa} />
            </div>
          )}
        </div>

        {/* Interview prep */}
        <div className="card p-5 md:col-span-2">
          <SectionTitle hint="Likely questions + STAR draft answers">Interview prep</SectionTitle>
          {prep && prep.items.length ? (
            <div className="space-y-3">
              <div className="max-h-96 space-y-3 overflow-auto pr-1 scroll-thin">
                {prep.items.map((item, i) => (
                  <div key={i}>
                    <div className="flex items-center gap-2">
                      <Chip tone={item.type === "technical" ? "brand" : "neutral"}>{item.type}</Chip>
                      <span className="text-sm font-medium text-white">{item.question}</span>
                    </div>
                    <div className="mt-1 whitespace-pre-wrap text-sm text-slate-300">{item.answer}</div>
                  </div>
                ))}
              </div>
              <button
                type="button"
                className="btn-ghost px-2.5 py-1 text-xs"
                disabled={loading.prep}
                onClick={runPrep}
              >
                Regenerate
              </button>
            </div>
          ) : (
            <div className="space-y-2">
              <button type="button" className="btn-ghost" disabled={loading.prep} onClick={runPrep}>
                {loading.prep ? <Spinner /> : null}
                {loading.prep ? "Preparing…" : "Generate interview prep"}
              </button>
              <ErrorBanner message={errors.prep} />
            </div>
          )}
        </div>
      </div>

      <div className="flex items-center justify-between gap-3">
        <button type="button" className="btn-ghost" onClick={onBack}>
          ← Back to match
        </button>
        {driveEnabled() ? (
          <div className="flex items-center gap-2">
            {driveMsg ? <span className="text-xs text-slate-400">{driveMsg}</span> : null}
            {driveUrl ? (
              <a
                href={driveUrl}
                target="_blank"
                rel="noreferrer"
                className="btn-ghost px-2.5 py-1 text-xs"
              >
                Open in Drive ↗
              </a>
            ) : null}
            <button
              type="button"
              className="btn-primary"
              disabled={driveBusy || !hasContent}
              onClick={saveToDrive}
              title={hasContent ? "Save this application to My Drive/OfferBen" : "Generate something first"}
            >
              {driveBusy ? <Spinner /> : null} Save to Drive
            </button>
          </div>
        ) : null}
      </div>
    </div>
  );
}

function workKey(w: { position?: string; name?: string; startDate?: string; endDate?: string }): string {
  return [w.position, w.name, w.startDate, w.endDate].join("|");
}

function titleMatches(title: string, ...fields: (string | undefined)[]): boolean {
  const t = (title || "").toLowerCase().trim();
  if (!t) return false;
  return fields
    .filter(Boolean)
    .some((f) => {
      const x = (f as string).toLowerCase().trim();
      return x.length > 1 && (t.includes(x) || x.includes(t));
    });
}

function CurationEditor({
  profile,
  dropped,
  pageTarget,
  onDropWork,
  onDropProject,
  onMoveWork,
  onMoveProject,
  onReorderWork,
  onReorderProject,
  onAddWork,
  onAddProject,
}: {
  profile: Profile;
  dropped: DroppedItem[];
  pageTarget: 1 | 2;
  onDropWork: (i: number) => void;
  onDropProject: (i: number) => void;
  onMoveWork: (i: number, dir: -1 | 1) => void;
  onMoveProject: (i: number, dir: -1 | 1) => void;
  onReorderWork: (from: number, to: number) => void;
  onReorderProject: (from: number, to: number) => void;
  onAddWork: (title: string) => void;
  onAddProject: (title: string) => void;
}) {
  // A dropped item is still "dropped" only if it's not currently in the resume
  // (so re-adding it removes it from this list).
  const stillDropped = dropped.filter((d) =>
    d.kind === "work"
      ? !profile.work.some((w) => titleMatches(d.title, w.position, w.name))
      : !profile.projects.some((p) => titleMatches(d.title, p.name)),
  );

  const est = estimatePages(profile);
  const overTarget = est > pageTarget + 0.08;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <span className="text-xs text-slate-400">
          Estimated length:{" "}
          <span className={overTarget ? "font-semibold text-amber-300" : "font-semibold text-emerald-300"}>
            ≈ {est.toFixed(1)} page{est >= 1.05 ? "s" : ""}
          </span>{" "}
          (target {pageTarget})
        </span>
        {overTarget ? (
          <span className="text-xs text-amber-300/80">over target — drop or trim items below</span>
        ) : null}
      </div>

      {profile.basics.summary ? (
        <p className="rounded-lg border border-white/10 bg-slate-900/40 p-3 text-sm text-slate-200">
          {profile.basics.summary}
        </p>
      ) : null}

      <ReorderList
        title="Experience — resume order"
        labels={profile.work.map((w) => {
          const base = [w.position, w.name].filter(Boolean).join(" · ") || "Untitled";
          const d = [w.startDate, w.endDate].filter(Boolean).join("–");
          return d ? `${base} (${d})` : base;
        })}
        onMove={onMoveWork}
        onDrop={onDropWork}
        onReorder={onReorderWork}
      />
      <ReorderList
        title="Projects — resume order"
        labels={profile.projects.map((p) => p.name || "Untitled")}
        onMove={onMoveProject}
        onDrop={onDropProject}
        onReorder={onReorderProject}
      />

      {stillDropped.length ? (
        <div>
          <div className="label">Dropped for this role — add back if you disagree</div>
          <ul className="space-y-1">
            {stillDropped.map((d, i) => (
              <li
                key={i}
                className="flex items-center gap-2 rounded-lg border border-dashed border-white/10 px-3 py-1.5 text-sm"
              >
                <span className="flex-1 truncate text-slate-400">
                  <span className="text-slate-300">{d.title}</span>
                  {d.reason ? ` — ${d.reason}` : ""}
                </span>
                <button
                  type="button"
                  className="btn-ghost px-2 py-0.5 text-xs"
                  onClick={() => (d.kind === "work" ? onAddWork(d.title) : onAddProject(d.title))}
                >
                  + Add back
                </button>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      <p className="text-xs text-slate-500">
        Drag (or ↑/↓) to reorder, ✕ to remove, “Add back” to re-include — the PDF updates
        instantly (no AI call). Download for the full formatted, ATS-safe resume.
      </p>
    </div>
  );
}

function ReorderList({
  title,
  labels,
  onMove,
  onDrop,
  onReorder,
}: {
  title: string;
  labels: string[];
  onMove: (i: number, dir: -1 | 1) => void;
  onDrop: (i: number) => void;
  onReorder: (from: number, to: number) => void;
}) {
  if (!labels.length) return null;
  return (
    <div>
      <div className="label">{title}</div>
      <ul className="space-y-1">
        {labels.map((label, i) => (
          <li
            key={i}
            draggable
            onDragStart={(e) => e.dataTransfer.setData("text/plain", String(i))}
            onDragOver={(e) => e.preventDefault()}
            onDrop={(e) => {
              e.preventDefault();
              const from = Number(e.dataTransfer.getData("text/plain"));
              if (!Number.isNaN(from)) onReorder(from, i);
            }}
            className="flex cursor-grab items-center gap-2 rounded-lg border border-white/10 bg-white/[0.02] px-3 py-1.5 text-sm active:cursor-grabbing"
          >
            <span className="select-none text-slate-600" title="Drag to reorder">
              ⠿
            </span>
            <span className="flex-1 truncate text-slate-200">{label}</span>
            <button
              type="button"
              className="px-1 text-slate-400 hover:text-white disabled:opacity-30"
              disabled={i === 0}
              onClick={() => onMove(i, -1)}
              title="Move up"
            >
              ↑
            </button>
            <button
              type="button"
              className="px-1 text-slate-400 hover:text-white disabled:opacity-30"
              disabled={i === labels.length - 1}
              onClick={() => onMove(i, 1)}
              title="Move down"
            >
              ↓
            </button>
            <button
              type="button"
              className="px-1 text-slate-500 hover:text-red-300"
              onClick={() => onDrop(i)}
              title="Remove from this resume"
            >
              ✕
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}
